"""
In-memory job store for AutoML Studio experiment management.

Manages experiment lifecycle state for background training jobs.
Each experiment is tracked from 'pending' through 'complete' or 'failed'.

Design decision: plain dict + threading.Lock is intentional.
No Redis or external broker needed for single-user ML engineer workloads.
Upgrade to Celery + Redis only when multi-user concurrency is required.
"""

import threading
import time
from typing import Any, Dict, List, Optional


# ---------------------------------------------------------------------------
# Status constants
# ---------------------------------------------------------------------------

STATUS_PENDING = "pending"
STATUS_RUNNING = "running"
STATUS_COMPLETE = "complete"
STATUS_FAILED = "failed"


# ---------------------------------------------------------------------------
# Stage labels — map pipeline step index to human-readable progress
# ---------------------------------------------------------------------------

STAGE_LABELS = {
    0: "Queued — waiting to start...",
    1: "Ingesting data...",
    2: "Validating dataset...",
    3: "Preprocessing features...",
    4: "Training models...",
    5: "Evaluating results...",
    6: "Complete",
}

STAGE_PROGRESS = {
    0: 0,
    1: 10,
    2: 25,
    3: 40,
    4: 60,
    5: 90,
    6: 100,
}


# ---------------------------------------------------------------------------
# Job store
# ---------------------------------------------------------------------------

class ExperimentStore:
    """
    Thread-safe in-memory store for experiment job state.

    All mutation happens through typed methods — never access
    _store directly from outside this class.

    Parameters
    ----------
    None

    Attributes
    ----------
    _store : Dict[str, Dict[str, Any]]
        Internal state keyed by experiment_id.
    _lock : threading.Lock
        Mutex protecting all read/write operations.
    """

    def __init__(self) -> None:
        self._store: Dict[str, Dict[str, Any]] = {}
        self._lock = threading.Lock()

    def create(
        self,
        experiment_id: str,
        target_column: str = "",
        dataset_path: str = "",
    ) -> None:
        """
        Register a new experiment in pending state.

        Parameters
        ----------
        experiment_id : str
            Unique experiment identifier generated by the pipeline.
        target_column : str
            Target column for this experiment — stored so features
            endpoint can return it correctly regardless of what
            config.data.target_column currently holds.
        dataset_path : str
            Absolute path to the dataset — stored so features endpoint
            can load sample values for the correct file.
        """
        with self._lock:
            self._store[experiment_id] = {
                "status": STATUS_PENDING,
                "progress": 0,
                "current_stage": STAGE_LABELS[0],
                "logs": [],
                "result": None,
                "error": None,
                "started_at": time.time(),
                "completed_at": None,
                "target_column": target_column,
                "dataset_path": dataset_path,
            }

    def set_stage(self, experiment_id: str, stage: int) -> None:
        """
        Advance the experiment to a named pipeline stage.

        Parameters
        ----------
        experiment_id : str
            Target experiment.
        stage : int
            Stage index (0–6). See STAGE_LABELS for mapping.
        """
        with self._lock:
            entry = self._store.get(experiment_id)
            if entry is None:
                return
            entry["status"] = STATUS_RUNNING
            entry["progress"] = STAGE_PROGRESS.get(stage, 0)
            entry["current_stage"] = STAGE_LABELS.get(stage, "Running...")

    def set_stage_label(
        self,
        experiment_id: str,
        label: str,
        progress: int,
    ) -> None:
        """
        Set stage label and progress directly by value.

        Used by ProgressTicker which works with labels and percentages
        rather than stage index integers.

        Parameters
        ----------
        experiment_id : str
        label : str
            Human-readable stage description.
        progress : int
            Progress percentage 0-100.
        """
        with self._lock:
            entry = self._store.get(experiment_id)
            if entry is None:
                return
            entry["status"] = STATUS_RUNNING
            entry["current_stage"] = label
            entry["progress"] = progress

    def append_log(self, experiment_id: str, message: str) -> None:
        """
        Append a log line to the experiment's log buffer.

        Parameters
        ----------
        experiment_id : str
            Target experiment.
        message : str
            Log line to append.
        """
        with self._lock:
            entry = self._store.get(experiment_id)
            if entry is None:
                return
            entry["logs"].append(message)

    def set_complete(
        self,
        experiment_id: str,
        result: Dict[str, Any],
    ) -> None:
        """
        Mark the experiment as successfully completed.

        Parameters
        ----------
        experiment_id : str
            Target experiment.
        result : Dict[str, Any]
            Full result payload (metrics, leaderboard, etc.).
        """
        with self._lock:
            entry = self._store.get(experiment_id)
            if entry is None:
                return
            entry["status"] = STATUS_COMPLETE
            entry["progress"] = 100
            entry["current_stage"] = STAGE_LABELS[6]
            entry["result"] = result
            entry["completed_at"] = time.time()

    def set_failed(self, experiment_id: str, error: str) -> None:
        """
        Mark the experiment as failed with an error message.

        Parameters
        ----------
        experiment_id : str
            Target experiment.
        error : str
            Exception message or human-readable failure reason.
        """
        with self._lock:
            entry = self._store.get(experiment_id)
            if entry is None:
                return
            entry["status"] = STATUS_FAILED
            entry["error"] = error
            entry["completed_at"] = time.time()

    def get(self, experiment_id: str) -> Optional[Dict[str, Any]]:
        """
        Retrieve the current state of an experiment.

        Parameters
        ----------
        experiment_id : str
            Target experiment.

        Returns
        -------
        Optional[Dict[str, Any]]
            Experiment state dict, or None if not found.
        """
        with self._lock:
            return self._store.get(experiment_id)

    def exists(self, experiment_id: str) -> bool:
        """
        Check whether an experiment ID is registered.

        Parameters
        ----------
        experiment_id : str
            Target experiment.

        Returns
        -------
        bool
            True if the experiment exists in the store.
        """
        with self._lock:
            return experiment_id in self._store


# ---------------------------------------------------------------------------
# Module-level singleton
# ---------------------------------------------------------------------------

# Single shared instance — imported directly by app.py and the worker.
# Lifetime matches the FastAPI process.
experiment_store = ExperimentStore()